In [1]:
import numpy as np
import scipy
from scipy import sparse


In [2]:
n=10
print([1]*n)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [3]:
for i in range(n):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [4]:
Y = np.array([5, 0, 6, 7, 8, 9, 2, 1, 4, 3])
matrix = sparse.coo_matrix(([1]*n, (Y, range(n))), shape = (10,n)).toarray()
print(matrix)

[[0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]]


In [14]:
X = np.arange(25).reshape(5, 5)
print(X)
iu = np.triu_indices(4, 4)
print(X[iu])

print(X[0])
print(X[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[]
[0 1 2 3 4]
[5 6 7 8 9]


In [15]:
Y = np.arange(5)
print(Y[0])
print(Y[1])

0
1
